default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 20 } %>
  timeout: 30000
  application_name: letter
  pragma:
    journal_mode: :wal
    synchronous: :normal
    cache_size: 20000
    foreign_keys: :on
    temp_store: :memory
    mmap_size: 268435456

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
    application_name: letter
  
  cache:
    <<: *default
    database: storage/cache_development.sqlite3
    application_name: letter
  
  queue:
    <<: *default
    database: storage/queue_development.sqlite3
    application_name: letter

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
    application_name: letter
    pragma:
      foreign_keys: :on
  
  cache:
    <<: *default
    database: storage/cache_test.sqlite3
    application_name: letter
  
  queue:
    <<: *default
    database: storage/queue_test.sqlite3
    application_name: letter

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
    application_name: letter
    pragma:
      journal_mode: :wal
      synchronous: :normal
      cache_size: 50000
      foreign_keys: :on
      temp_store: :memory
      mmap_size: 536870912
  
  queue:
    <<: *default
    database: storage/queue_production.sqlite3
    application_name: letter
    pragma:
      journal_mode: :wal
      synchronous: :normal
      cache_size: 10000
      foreign_keys: :on
      temp_store: :memory
      mmap_size: 268435456
  
  cable:
    <<: *default
    database: storage/cable_production.sqlite3
    application_name: letter
    pragma:
      journal_mode: :wal
      synchronous: :normal
      cache_size: 10000
      foreign_keys: :on
      temp_store: :memory
      mmap_size: 268435456
  
  cache:
    <<: *default
    database: storage/cache_production.sqlite3
    application_name: letter
    pragma:
      journal_mode: :wal
      synchronous: :normal
      cache_size: 10000
      foreign_keys: :on
      temp_store: :memory
      mmap_size: 268435456
